import psycopg2
from colorama import Cursor

con = psycopg2.connect(database="sistema",
                         host="localhost",
                         user="postgres",
                         password="felicidade",
                         port="5432");

cur = con.cursor()
cur.execute("""CREATE TABLE CATEGORIAS(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(30) UNIQUE NOT NULL);""")

cur.execute("""CREATE TABLE MARCAS(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(30) UNIQUE NOT NULL);""")

cur.execute("""CREATE TABLE PRODUTOS(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
ESTOQUE NUMERIC(7),
DATA_CADASTRO DATE,
ID_CATEGORIA INTEGER NOT NULL,
ID_MARCA INTEGER NOT NULL,
PRECO_VENDA NUMERIC(10,2),
CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID),
CONSTRAINT FK_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCAS(ID));""")

cur.execute("""CREATE TABLE LOTES
(ID SERIAL PRIMARY KEY,
ID_PRODUTO INTEGER NOT NULL,
LOTE VARCHAR(20),
VALIDADE DATE,
CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID));""")

cur.execute("""CREATE TABLE MOV(
ID SERIAL PRIMARY KEY,
MOVIMENTACAO VARCHAR(15),
ENT_SAI VARCHAR(10),
ESTOQUE NUMERIC(5) NOT NULL,
DATA_MOV DATE,
ID_PRODUTO INTEGER NOT NULL,
NOME_PRODUTO VARCHAR(100) NOT NULL,
CONSTRAINT FK_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID));""")

con.commit()
cur.close()
con.close()





